services:
  - type: web
    name: ERP-Template
    runtime: python
    plan: free
    rootDir: ERP-Template
    buildCommand: "./setup.sh"
    startCommand: gunicorn ERP-Template.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ERP-Template.settings
      - key: DATABASE_URL
        fromDatabase:
          name: django-rest-db
          property: connectionString