services:
  - type: web
    name: ERP-Template
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    rootDir: ERP-Template
    startCommand: gunicorn ERP-Template.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ERP-Template.settings
      - key: DATABASE_URL
        fromDatabase:
          name: django-rest-db
          property: postgresql://djangorestdb_jl9c_user:WGKJS5NmaguTocpimck3zbVnNtJTQMsi@dpg-cpq9achu0jms738rv7r0-a/djangorestdb_jl9c