# Generated by Django 5.0.3 on 2024-07-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaction',
            name='action_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('button', 'Button')], default='dropdown', max_length=255),
        ),
    ]
