# Generated by Django 5.0.3 on 2024-07-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modelaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
