# Generated by Django 5.0.3 on 2024-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logmessage_action_alter_logmessage_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
