# Generated by Django 5.0.3 on 2024-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logmessage_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaction',
            name='action_type',
            field=models.CharField(choices=[('button', 'Button'), ('dropdown', 'Dropdown')], default='dropdown', max_length=255),
        ),
    ]
