# Generated by Django 5.0.3 on 2024-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_modelaction_action_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelaction',
            old_name='name',
            new_name='list_name',
        ),
        migrations.AddField(
            model_name='modelaction',
            name='detail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modelaction',
            name='action_type',
            field=models.CharField(choices=[('button', 'Button'), ('dropdown', 'Dropdown')], default='dropdown', max_length=255),
        ),
    ]
