# Generated by Django 5.0.3 on 2024-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_modelaction_list_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelaction',
            name='include_pk',
            field=models.BooleanField(default=True),
        ),
    ]
