# Generated by Django 5.0.3 on 2024-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_is_deleted'),
        ('orders', '0005_order_is_deleted_orderitem_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=models.SET('CANCELLED'), to='orders.order'),
        ),
    ]
