# Generated by Django 5.0.3 on 2024-03-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('InventoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('LocationID', models.IntegerField()),
                ('QuantityOnHand', models.IntegerField()),
                ('AverageCost', models.IntegerField()),
                ('LastReceivedDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=255)),
                ('PartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parts.parts')),
            ],
        ),
    ]
