# Generated by Django 5.0.3 on 2024-03-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parts',
            fields=[
                ('PartID', models.IntegerField(primary_key=True, serialize=False)),
                ('PartName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('CatagoryID', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Cost', models.FloatField()),
                ('MinimumStockLevel', models.IntegerField()),
                ('ReorderQuantity', models.IntegerField()),
                ('LeadTime', models.IntegerField()),
                ('SupplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suppliers.supplier')),
            ],
        ),
    ]
