# Generated by Django 5.0.3 on 2024-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_created_at_part_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
