# Generated by Django 5.0.3 on 2024-03-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceHeaders',
            fields=[
                ('InvoiceID', models.IntegerField(primary_key=True, serialize=False)),
                ('OrderID', models.IntegerField()),
                ('CustomerID', models.IntegerField()),
                ('InvoiceDate', models.DateTimeField()),
                ('DueDate', models.DateTimeField()),
                ('TotalAmount', models.FloatField()),
                ('Status', models.CharField(max_length=255)),
                ('TaxAmount', models.FloatField()),
                ('DiscountAmount', models.FloatField()),
                ('ShippingAmount', models.IntegerField()),
                ('PaymentTerms', models.TextField()),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='invoiceDetails',
            fields=[
                ('InvoiceDetailID', models.IntegerField(primary_key=True, serialize=False)),
                ('InvoiceID', models.IntegerField()),
                ('Description', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.FloatField()),
                ('LineTotal', models.FloatField()),
                ('Discount', models.FloatField()),
                ('TaxRate', models.FloatField()),
                ('TaxAmount', models.FloatField()),
                ('PartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parts.parts')),
            ],
        ),
    ]
