# Generated by Django 5.0.3 on 2024-03-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('SupplierID', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('ContactTitle', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField()),
                ('Notes', models.TextField()),
            ],
        ),
    ]
